ClearSkyProperties/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ClearSkyProperties.Data;
using ClearSkyProperties.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace ClearSkyProperties.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;
        public HomeController(ApplicationDbContext context, IConfiguration config)
        {
            _context = context;
            _config = config;
        }

        [HttpGet]
        public string Get()
        {
            var value = _config["SendGridKey"];
            return "Value for Secret [SendGridKey] is : " + value;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Properties.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClearSkyProperties/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClearSkyProperties.Data;
using ClearSkyProperties.Models;
using Microsoft.AspNetCore.Authorization;

namespace ClearSkyProperties.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PropertiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            return View(await _context.Properties.ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        public async Task<IActionResult> Enquire(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            PropertyAndEnquiry propertyAndEnquiry = new PropertyAndEnquiry();
            propertyAndEnquiry.Property = @property;
            return PartialView("Enquire", propertyAndEnquiry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEnquiry([Bind("ID,PropertyID,PropertyName,FirstName,LastName,PhoneNumber,Email,Msg")] Enquiry @enquiry)
        {
            if (ModelState.IsValid)
            {
                //Find the Property related and increment the 'Enquiries' column
                Property property = new Property { ID = enquiry.PropertyID };
                _context.Properties.Attach(property).Property(x => x.Enquiries).CurrentValue += 1;
                //Add the Enquiry to the Enquiries table.
                _context.Add(@enquiry);
                await _context.SaveChangesAsync();
                TempData["alertMessage"] = "Your enquiry has been succesfully received.";
                return RedirectToAction(nameof(Index));
            }
            return View(@enquiry);
        }


        private bool PropertyExists(int id)
        {
            return _context.Properties.Any(e => e.ID == id);
        }
    }
}

ClearSkyProperties/Views/Home/Index.cshtml
@model IEnumerable<ClearSkyProperties.Models.Property>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Clear Sky!</h1>
    <hr class="hr-small" />
</div>
<div class="container py-4 carousel-size">
    <div id="propertyCarousel" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#propertyCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#propertyCarousel" data-slide-to="1"></li>
            <li data-target="#propertyCarousel" data-slide-to="2"></li>
            <li data-target="#propertyCarousel" data-slide-to="3"></li>
            <li data-target="#propertyCarousel" data-slide-to="4"></li>
        </ul>
        <div class="carousel-inner " role="listbox">
            @{int i = 0;}
            @foreach (var item in Model)
            {
                i++;
                var active = i == 1 ? "active" : "";
                <div class="carousel-item @active">
                    <a asp-controller="Properties" asp-action="Details" asp-route-id="@item.ID">
                        <img class="image-size" src="@Url.Content(@item.Img)" alt="">
                    </a>
                    <div class="overlay-bar-top">
                        <p class="carousel-label-left">@item.Name</p>
                        <p class="carousel-label-right">
                            @{
                                int price = Int32.Parse(Html.Raw(item.Price).ToString());
                                decimal result = price / 100m;
                                var priceString = result.ToString("c");
                                                } @priceString
                                            </p>
                    </div>
                    <div class="overlay-bar-bot"></div>
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#propertyCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon icon-style"></span>
        </a>
        <a class="carousel-control-next" href="#propertyCarousel" data-slide="next">
            <span class="carousel-control-next-icon icon-style"></span>
        </a>
    </div>
</div>
<div>
    <hr class="hr-small" />
    <p>Welcome to Clear Sky Properties, please browse our stunning properties in the menu above!</p>
    <p>Perhaps this time will be the time you place an enquiry!</p>
</div>

<style>
    .hr-small {
        padding-top: 1%;
        margin-bottom: 0px;
        width: 50%;
    }

    .image-size {
        width: 100%;
        height: 440px;
    }

    .carousel-size {
        width: 50vw;
        height: 460px;
    }

    .carousel-label-left {
        position: absolute;
        top: 1px;
        left: 10px;
        font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
        font-size: 29px;
        letter-spacing: 1px;
        word-spacing: 2px;
        color: #FFFFFF;
        font-weight: 700;
        text-decoration: none solid rgb(68, 68, 68);
        font-style: normal;
        font-variant: normal;
        text-transform: none;
    }

    .carousel-label-right {
        position: absolute;
        top: 10px;
        right: 10px;
        font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
        font-size: 20px;
        letter-spacing: 1px;
        word-spacing: 2px;
        color: #FFFFFF;
        font-weight: 700;
        text-decoration: none solid rgb(68, 68, 68);
        font-style: normal;
        font-variant: normal;
        text-transform: none;
    }

    .overlay-bar-top {
        background-color: rgba(0,0,0,0.4);
        height: 42px;
        width: 100%;
        position: absolute;
        top: 1px;
    }

    .overlay-bar-bot {
        background-color: rgba(0,0,0,0.4);
        height: 42px;
        width: 100%;
        position: absolute;
        bottom: 1px;
    }

    .carousel-control-prev-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='111111' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
    }

    .carousel-control-next-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='111111' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important; 

    }

</style>